language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-player-plugin' ]; then cd .. && eval "mv $currentfolder generator-player-plugin" && cd generator-player-plugin; fi

