//This file is generated by bin/hook.js
var template = require('lodash.template');
module.exports = {
<% templates.each(function(template) { %>
  '<%= template.name %>': template('<%= template.content %>'),
<% }); %>
  CSS: {
    <% styles.each(function(style) { %>
      '<%= style.name %>': '<%= style.content %>',
    <% }); %>
  }
};
