//This file is generated by bin/hook.js
var template = require('lodash.template');
module.exports = {
<% _.each(templates, function(template) { %>
  '<%= template.name %>': template('<%= template.content %>'),
<% }); %>
  CSS: {
    <% _.each(styles, function(style) { %>
      '<%= style.name %>': '<%= style.content %>',
    <% }); %>
  }
};
